name: AS_TESTS

on:
  push:
    branches:
      - 'main'
  workflow_run:
    workflows: [ Labeler ]
    types:
      - completed
  workflow_dispatch:

# Only run the latest job
concurrency:
  group: '${{ github.workflow }} @ ${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  as_tests-test:
    strategy:
      matrix:
        java-version: [ 17 ]
    name: AS_TESTS test with JDK ${{ matrix.java-version }}
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check for `testing/as_tests` label
        id: check-label
        run: |
          echo "should_skip=false" >> $GITHUB_OUTPUT
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "Checking labels on PR #${{ github.event.pull_request.number }}..."
            LABELS=$(gh pr view ${{ github.event.pull_request.number }} --json labels --jq '.labels[].name')
            echo "Labels found: $LABELS"
            if ! echo "$LABELS" | grep -q "^testing/rts$"; then
              echo "Label 'testing/as_tests' not found. Skipping job."
              echo "should_skip=true" >> $GITHUB_OUTPUT
            fi
          fi
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Set up JDK ${{ matrix.java-version }}
        if: steps.check-label.outputs.should_skip != 'true'
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}

      - name: Cache Maven dependencies
        if: steps.check-label.outputs.should_skip != 'true'
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository/*/*
            !~/.m2/repository/org/jboss
            !~/.m2/repository/org/wildfly
          key: maven-${{ runner.os }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: AS_TESTS testing profile
        if: steps.check-label.outputs.should_skip != 'true'
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"  
          WORKSPACE=$PWD PROFILE=AS_TESTS ./scripts/hudson/narayana.sh

      - uses: actions/upload-artifact@v4
        if: steps.check-label.outputs.should_skip != 'true' && always()
        with:
          name: as_tests-logs-jdk${{ matrix.java-version }}
          path: |
            **/*.*log*
            **/ObjectStore*/**  
            **/tx-object-store/**
            **/*tx-object-store.zip
            **/target/*surefire-reports*/**
            **/target/*failsafe-reports*/**
            jboss-as/build/target/wildfly-*/**
            jboss-as/dist/target/wildfly-*.zip
            jboss-as/dist/target/wildfly-*/standalone/log/
          if-no-files-found: error
