name: jacoco

on:
  workflow_call:
    inputs:
      jdk_version:
        description: 'JDK version'
        required: true
        type: string
      pull_request_repo:
        description: 'Repository to check out'
        required: true
        type: string
        default: 'jbosstm/narayana'
      pull_request_ref:
        description: 'Branch or commit to test'
        required: true
        type: string
      narayana_artifact_name:
        description: 'Narayana Maven repository artifact name'
        required: true
        type: string
      wildfly_artifact_name:
        description: 'WIldFly Maven repository artifact name'
        required: true
        type: string
      jboss_as_zip_name:
        description: 'JBoss/WildFly zip artifact name'
        required: true
        type: string

# Only run the latest job
concurrency:
  group: 'jacoco @ ${{ github.workflow }} @ ${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  jacoco-test:
    name: JACOCO axis with JDK ${{ inputs.jdk_version }}
    runs-on: ubuntu-latest

    steps:
      - name: Log run context
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Repository: ${{ inputs.pull_request_repo || github.repository }}"
          echo "Branch/Ref: ${{ inputs.pull_request_ref || github.ref }}"
          echo "Narayana artifacts: ${{ inputs.narayana_artifact_name }}"
          echo "WildFly artifacts: ${{ inputs.wildfly_artifact_name }}"
          echo "WildFly zip name: ${{ inputs.jboss_as_zip_name }}"

      - name: Checkout code
        uses: actions/checkout@v5
        with:
          repository: '${{ inputs.pull_request_repo || github.repository }}'
          ref: ${{ inputs.pull_request_ref || github.ref }}

      - name: Configure and restart PostgreSQL
        uses: ./.github/actions/postgres_setup_ubuntu_runner
        with:
          target_db: ${{ env.TARGET_DB }}

      - name: Starts and configure MySQL
        uses: ./.github/actions/mysql_setup_ubuntu_runner

      - name: Starts and configure Oracle
        uses: ./.github/actions/oracle_setup_ubuntu_runner

      - name: Pull, starts and configure DB2
        uses: ./.github/actions/db2_setup_ubuntu_runner

      - name: Set up JDK ${{ inputs.jdk_version }}
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ inputs.jdk_version }}

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository/*/*/*
            !~/.m2/repository/org/jboss/narayana
            !~/.m2/repository/org/wildfly/*
          key: maven-${{ runner.os }}

      - name: Download Narayana Maven repository
        uses: actions/download-artifact@v5
        with:
          name: ${{ inputs.narayana_artifact_name }}
          path: ~/.m2/repository/org/jboss/narayana

      - name: Download WildFly Maven repository
        uses: actions/download-artifact@v5
        with:
          name: ${{ inputs.wildfly_artifact_name }}
          path: ~/.m2/repository/org/wildfly

      - name: Download WildFly zip
        uses: actions/download-artifact@v5
        with:
          name: ${{ inputs.jboss_as_zip_name }}
          path: ${{ github.workspace }}
          merge-multiple: true

      - name: Unzip WildFly zip
        run: |
          unzip wildfly-*.zip
          dir=$(unzip -Z -1 wildfly-*.zip | head -n1 | cut -d/ -f1)
          mv "$dir" wildfly

      - name: jacoco testing axis
        id: jacoco_axis
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          JBOSS_HOME=${{ github.workspace }}/wildfly AS_BUILD=0 NARAYANA_BUILD=0 PROFILE=JACOCO ./.github/scripts/narayana.sh

      - uses: actions/upload-artifact@v4
        if: ${{ failure() && steps.jacoco_axis.conclusion == 'failure' || cancelled() && steps.jacoco_axis.conclusion == 'cancelled' }}
        with:
          retention-days: 30
          name: jacoco-logs-jdk${{ inputs.jdk_version }}
          path: |
            **/*.*log*
            **/ObjectStore*/**
            **/tx-object-store/**
            **/*tx-object-store.zip
            **/target/*surefire-reports*/**
            **/target/*failsafe-reports*/**
          if-no-files-found: warn
