name: qa_jts_openjdkorb

on:
  workflow_call:
    inputs:
      jdk_version:
        description: 'JDK version'
        required: true
        type: string
      pull_request_repo:
        description: 'Repository to check out'
        required: true
        type: string
        default: 'jbosstm/narayana'
      pull_request_ref:
        description: 'Branch or commit to test'
        required: true
        type: string

# Only run the latest job
concurrency:
  group: 'qa_jts_openjdkorb @ ${{ github.workflow }} @ ${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  qa_jts_openjdkorb-test:
    name: QA_JTS_OPENJDKORB axis with JDK ${{ inputs.jdk_version }}
    timeout-minutes: 360
    runs-on: ubuntu-latest
    env:
      TARGET_DB: "jbossts"

    steps:
      - name: Log run context
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Repository: ${{ inputs.pull_request_repo || github.repository }}"
          echo "Branch/Ref: ${{ inputs.pull_request_ref || github.ref }}"

      - name: Checkout code
        uses: actions/checkout@v5
        with:
          repository: '${{ inputs.pull_request_repo || github.repository }}'
          ref: ${{ inputs.pull_request_ref || github.ref }}

      - name: Configure and restart PostgreSQL
        env:
          PGUSER: "postgres"
          TARGET_DB: ${{ env.TARGET_DB }}
        run: |
          sudo sed -i '/^host/s/scram-sha-256/trust/' /etc/postgresql/*/main/pg_hba.conf
          sudo systemctl start postgresql.service
          pg_isready
          sudo -u postgres psql -v target_db=${{ env.TARGET_DB }} -v pguser=postgres < .github/databases/postgres/init.sql
          sudo systemctl restart postgresql.service
          pg_isready

      - name: Configure MySQL
        run: |
          sudo systemctl start mysql.service
          mysql -h 127.0.0.1 -uroot -proot < .github/databases/mysql/init.sql

      - name: Configure Oracle
        uses: gvenzl/setup-oracle-free@v1
        with:
          tag: "full"
          app-user: "jbossts"
          app-user-password: "jbossts"
          container-runtime: "docker"
          setup-scripts: "${{ github.workspace }}/.github/databases/oracle"

      - name: Pull and configure DB2
        run: |
          docker pull icr.io/db2_community/db2
          cd ${{ github.workspace }}/.github/databases/db2
          mkdir docker
          docker run -h db2server --name db2server --restart=always --detach --privileged=true \
            -p 50000:50000 --env-file env_list \
            -v docker:/database icr.io/db2_community/db2
          docker exec db2server bash -c "
            useradd -m db2 && echo 'db2:db2' | chpasswd
            useradd -m db22 && echo 'db22:db22' | chpasswd
          "
          docker logs -f db2server | sed "/Setup has completed/q"
          docker cp init.sql db2server:/tmp/init.sql
          docker exec db2server su - db2inst1 -c "db2 -tvf /tmp/init.sql"

      - name: Set up JDK ${{ inputs.jdk_version }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ inputs.jdk_version }}

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/jboss/narayana
            !~/.m2/repository/org/wildfly
          key: maven-${{ runner.os }}
          restore-keys: maven-${{ runner.os }}-

      - name: QA_JTS_OPENJDKORB testing axis
        id: qa_jts_openjdkorb
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          WORKSPACE=$PWD PROFILE=QA_JTS_OPENJDKORB ./.github/scripts/narayana.sh

      - uses: actions/upload-artifact@v4
        if: ${{ failure() && steps.qa_jts_openjdkorb.conclusion == 'failure' }}
        with:
          retention-days: 30
          name: qa_jts_openjdkorb-logs-jdk${{ inputs.jdk_version }}
          path: qa/testoutput/**/*
          if-no-files-found: warn

      - name: Stop and delete DB2
        run: |
          docker stop db2server
          docker rm db2server
